#application.properties
#spring.application.name=
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create

spring:
  application:
    name: ecom-application

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 9090