#application.properties
#spring.application.name=
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
#management.endpoints.web.exposure.include=*
# endpoint.health.show-details= always
spring:
  application:
    name: ecom-application
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb?serverTimezone=IST
    username: admin
    password: admin
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
    shutdown:
      access: none
  info:
    env:
      enabled: true

info:
    app:
      name: MyApp
      version: 1.0.0

